spring:
  application:
    name: scoring-service

app:
  scoring:
    use-remote: false
  cors:
    dev-mode: true

decision-engine:
  url: http://localhost:8081

server:
  port: 8080

springdoc:
  show-actuator: true

scalar:
  actuatorEnabled: true
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
